### PR TITLE
ToTypeOrDefault when source == null

### PR DESCRIPTION
**Pull request by mojinxun**
when I use ToInt32OrDefault()

source is null
so I want get the defaultValue

but Convert.ToInt32 can't throw a Excetion , just default(int) = 0

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @mojinxun ,

Thank you for this pull request.

The problem is currently more our "ToInt32" is a shortcut to Convert.ToInt32 and you are currently changing the default behavior.

As I currently understand your problem perfectly, we must decide on our side how we should treat it.

We will review your pull request and try to provide a solution next week.

Best Regards,

Jonathan

**Comment by mojinxun** [comment]
ok, I benefited from the project.

Hope you get better and better

**Comment by mojinxun** [comment]
what about it?

**Comment by JonathanMagnan** [comment]
Sorry for the delay,

I will look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mojinxun ,

I really don't know what to do currently with this request since we try to be backward compatible. So far, we don't like a lot adding some options to treat null as an empty string or creating more method overload to handle this scenario.

Perhaps you could try to use instead `ToOrDefault<int>(null, 5)` method which already does exactly your default behavior and use the default value when null is specified?

Best Regards,

Jonathan

**Comment by mojinxun** [comment]
maybe we can do this

public static bool ToBooleanOrDefault(this object @this, bool defaultValue, bool isIgnoreNull = false)

**Comment by JonathanMagnan** [comment]
It was part of solutions we don't like a lot.

If we find nothing better, we will implement this one over the weekend and make sure we have a new version ready for Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mojinxun ,

The v2.0.12 has been finally released.

An overload has you suggested has been added.

Let me know if we can close this pull request

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: Feel free to re-open if needed.

**Pull request closed without merging**
