### PR TITLE
New IList<T> extension method - Swap

### PR DESCRIPTION
**Pull request by falwickster**
Hello

This is my first pull request, this is a new extension method to replace an item in a collection when the item we want to change exists in a collection. Otherwise it won't make any changes.

EDIT: I have noticed that all ICollection methods are  void or bool, so I rewrote the method to be void. I have it on my fork.

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @falwickster ,

Thank you for your contribution.

This project is currently still on hold on our side for a few weeks (we have to many requests) but we will certainly look at it when we will be able.

Beside this, I'm this not sure if I like the second implementation or not.

We probably expect when swapping an item, the same position will remain as your first implementation.
Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by falwickster** [comment]
Hello @JonathanMagnan,

Thanks for feedback. I replaced this ICollection method to IList method, because as far as I know ICollection doesn't store indexes, so swaping items with keeping its position is problematic.

Best Regards

**Comment by JonathanMagnan** [comment]
Thank a lot ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @falwickster ,

Sorry for the long waiting, we had to complete the support to .NET Standard first.

Your method has been added

Thank you for your contribution ;)

Best Regards,

Jonathan

**Pull request merged**
